#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : sortedcontainers
Version  : 2.1.0
Release  : 8
URL      : https://files.pythonhosted.org/packages/29/e0/135df2e733790a3d3bcda970fd080617be8cea3bd98f411e76e6847c17ef/sortedcontainers-2.1.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/29/e0/135df2e733790a3d3bcda970fd080617be8cea3bd98f411e76e6847c17ef/sortedcontainers-2.1.0.tar.gz
Summary  : Sorted Containers -- Sorted List, Sorted Dict, Sorted Set
Group    : Development/Tools
License  : Apache-2.0
Requires: sortedcontainers-license = %{version}-%{release}
Requires: sortedcontainers-python = %{version}-%{release}
Requires: sortedcontainers-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : tox

%description
========================
        
        `Sorted Containers`_ is an Apache2 licensed `sorted collections library`_,
        written in pure-Python, and fast as C-extensions.
        
        Python's standard library is great until you need a sorted collections
        type. Many will attest that you can get really far without one, but the moment
        you **really need** a sorted list, sorted dict, or sorted set, you're faced
        with a dozen different implementations, most using C-extensions without great
        documentation and benchmarking.
        
        In Python, we can do better. And we can do it in pure-Python!

%package license
Summary: license components for the sortedcontainers package.
Group: Default

%description license
license components for the sortedcontainers package.


%package python
Summary: python components for the sortedcontainers package.
Group: Default
Requires: sortedcontainers-python3 = %{version}-%{release}

%description python
python components for the sortedcontainers package.


%package python3
Summary: python3 components for the sortedcontainers package.
Group: Default
Requires: python3-core

%description python3
python3 components for the sortedcontainers package.


%prep
%setup -q -n sortedcontainers-2.1.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1542913772
python3 setup.py build

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}/usr/lib/python3.7/site-packages python3 setup.py test
%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/sortedcontainers
cp LICENSE %{buildroot}/usr/share/package-licenses/sortedcontainers/LICENSE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/sortedcontainers/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
